import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { isSignedIn } = useUser();

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-700">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {isSignedIn ? <SignOutButton /> : <SignInButton />}
          <div>
            {data?.map((post) => (
              <div className="py-2">{post.content}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
